// AUTO-GENERATED by tools/gen_registry.py — DO NOT EDIT.
#include <struct_view/NameRegistry.hpp>
#include <struct_view/ValueProvider.hpp>
#include <struct_view/DeviceCtx.hpp>
#include <cstddef>
#include <cstdio>
#include <string>
#include <type_traits>

void registerStructViewNames(sv::NameRegistry& reg) {
    reg.registerProvider("time", sv::makeProvider(
        [](const void* p, const sv::DeviceCtx&) -> std::string {
            const Event* s = static_cast<const Event*>(p);
            char buf[64];
            std::snprintf(buf, sizeof(buf), "%llu", (unsigned long long)s->timestamp);
            return std::string(buf);
        }), "时间戳");
    reg.registerStruct("person", sv::Navigator(
        [](const void* p) -> const void* {
            const Event* s = static_cast<const Event*>(p);
            return static_cast<const void*>(s->person);
        }), {"name", "age"}, "-", "人体信息");
    reg.registerStruct("rect", sv::Navigator(
        [](const void* p) -> const void* {
            const Event* s = static_cast<const Event*>(p);
            return static_cast<const void*>(&s->rect);
        }), {"x", "y", "w", "h", "tags"}, ",", "检测框");
    reg.registerScalarArray("feat_ids",
        [](const void* p, std::size_t i) -> std::string {
            const Event* s = static_cast<const Event*>(p);
            static_assert(std::extent_v<decltype(s->feature_ids)> >= 8,
                          "struct_view: feature_ids length drift (schema count=8)");
            char buf[64];
            std::snprintf(buf, sizeof(buf), "%d", (int)s->feature_ids[i]);
            return std::string(buf);
        }, 8, "-", "特征ID列表");
    reg.registerStructArray("boxes", sv::IndexedNavigator(
        [](const void* p, std::size_t i) -> const void* {
            const Event* s = static_cast<const Event*>(p);
            static_assert(std::extent_v<decltype(s->boxes)> >= 4,
                          "struct_view: boxes length drift (schema count=4)");
            return &s->boxes[i];
        }), {"x", "y", "w", "h", "tags"}, 4, ",", "|", "检测框数组");
    reg.registerProvider("name", sv::makeProvider(
        [](const void* p, const sv::DeviceCtx&) -> std::string {
            const PersonInfo* s = static_cast<const PersonInfo*>(p);
            return std::string((const char*)s->name);
        }), "姓名");
    reg.registerProvider("age", sv::makeProvider(
        [](const void* p, const sv::DeviceCtx&) -> std::string {
            const PersonInfo* s = static_cast<const PersonInfo*>(p);
            char buf[64];
            std::snprintf(buf, sizeof(buf), "%d", (int)s->age);
            return std::string(buf);
        }), "年龄");
    reg.registerProvider("x", sv::makeProvider(
        [](const void* p, const sv::DeviceCtx&) -> std::string {
            const Box* s = static_cast<const Box*>(p);
            char buf[64];
            std::snprintf(buf, sizeof(buf), "%d", (int)s->x);
            return std::string(buf);
        }), "横坐标");
    reg.registerProvider("y", sv::makeProvider(
        [](const void* p, const sv::DeviceCtx&) -> std::string {
            const Box* s = static_cast<const Box*>(p);
            char buf[64];
            std::snprintf(buf, sizeof(buf), "%d", (int)s->y);
            return std::string(buf);
        }), "纵坐标");
    reg.registerProvider("w", sv::makeProvider(
        [](const void* p, const sv::DeviceCtx&) -> std::string {
            const Box* s = static_cast<const Box*>(p);
            char buf[64];
            std::snprintf(buf, sizeof(buf), "%d", (int)s->w);
            return std::string(buf);
        }), "宽");
    reg.registerProvider("h", sv::makeProvider(
        [](const void* p, const sv::DeviceCtx&) -> std::string {
            const Box* s = static_cast<const Box*>(p);
            char buf[64];
            std::snprintf(buf, sizeof(buf), "%d", (int)s->h);
            return std::string(buf);
        }), "高");
    reg.registerScalarArray("tags",
        [](const void* p, std::size_t i) -> std::string {
            const Box* s = static_cast<const Box*>(p);
            static_assert(std::extent_v<decltype(s->tags)> >= 2,
                          "struct_view: tags length drift (schema count=2)");
            char buf[64];
            std::snprintf(buf, sizeof(buf), "%d", (int)s->tags[i]);
            return std::string(buf);
        }, 2, "-", "标签");
    reg.registerProvider("camera", sv::makeProvider(
        [](const void*, const sv::DeviceCtx& base) -> std::string {
            const MyDeviceCtx& ctx = static_cast<const MyDeviceCtx&>(base);
            return ctx.cameraId();
        }), "摄像头编号");
}
