// AUTO-GENERATED by tools/gen_registry.py — DO NOT EDIT.
#include <struct_view/NameRegistry.hpp>
#include <struct_view/ValueProvider.hpp>
#include <struct_view/DeviceCtx.hpp>
#include <cstdio>
#include <string>

void registerStructViewNames(sv::NameRegistry& reg) {
    reg.registerProvider("time", sv::makeProvider(
        [](const void* p, const sv::DeviceCtx&) -> std::string {
            const Event* s = static_cast<const Event*>(p);
            char buf[256];
            std::snprintf(buf, sizeof(buf), "%llu", (unsigned long long)s->timestamp);
            return std::string(buf);
        }));
    reg.registerStruct("person", sv::Navigator(
        [](const void* p) -> const void* {
            const Event* s = static_cast<const Event*>(p);
            return static_cast<const void*>(s->person);
        }), "person");
    reg.registerStruct("rect", sv::Navigator(
        [](const void* p) -> const void* {
            const Event* s = static_cast<const Event*>(p);
            return static_cast<const void*>(&s->rect);
        }), "rect");
    reg.registerProvider("name", sv::makeProvider(
        [](const void* p, const sv::DeviceCtx&) -> std::string {
            const PersonInfo* s = static_cast<const PersonInfo*>(p);
            char buf[256];
            std::snprintf(buf, sizeof(buf), "%s", (const char*)s->name);
            return std::string(buf);
        }));
    reg.registerProvider("age", sv::makeProvider(
        [](const void* p, const sv::DeviceCtx&) -> std::string {
            const PersonInfo* s = static_cast<const PersonInfo*>(p);
            char buf[256];
            std::snprintf(buf, sizeof(buf), "%d", (int)s->age);
            return std::string(buf);
        }));
    reg.registerProvider("x", sv::makeProvider(
        [](const void* p, const sv::DeviceCtx&) -> std::string {
            const Box* s = static_cast<const Box*>(p);
            char buf[256];
            std::snprintf(buf, sizeof(buf), "%d", (int)s->x);
            return std::string(buf);
        }));
    reg.registerProvider("y", sv::makeProvider(
        [](const void* p, const sv::DeviceCtx&) -> std::string {
            const Box* s = static_cast<const Box*>(p);
            char buf[256];
            std::snprintf(buf, sizeof(buf), "%d", (int)s->y);
            return std::string(buf);
        }));
    reg.registerProvider("w", sv::makeProvider(
        [](const void* p, const sv::DeviceCtx&) -> std::string {
            const Box* s = static_cast<const Box*>(p);
            char buf[256];
            std::snprintf(buf, sizeof(buf), "%d", (int)s->w);
            return std::string(buf);
        }));
    reg.registerProvider("h", sv::makeProvider(
        [](const void* p, const sv::DeviceCtx&) -> std::string {
            const Box* s = static_cast<const Box*>(p);
            char buf[256];
            std::snprintf(buf, sizeof(buf), "%d", (int)s->h);
            return std::string(buf);
        }));
    reg.registerProvider("camera", sv::makeProvider(
        [](const void*, const sv::DeviceCtx& base) -> std::string {
            const MyDeviceCtx& ctx = static_cast<const MyDeviceCtx&>(base);
            return ctx.cameraId();
        }));
}
