// AUTO-GENERATED by tools/gen_registry.py — DO NOT EDIT.
#include <struct_view/NameRegistry.hpp>
#include <struct_view/ValueProvider.hpp>
#include <struct_view/DeviceCtx.hpp>
#include <cstddef>
#include <cstdio>
#include <string>
#include <type_traits>

void registerStructViewNames(sv::NameRegistry& reg) {
    reg.registerProvider("time", sv::makeProvider(
        [](const void* p, const sv::DeviceCtx&) -> std::string {
            const Event* s = static_cast<const Event*>(p);
            char buf[256];
            std::snprintf(buf, sizeof(buf), "%llu", (unsigned long long)s->timestamp);
            return std::string(buf);
        }));
    reg.registerStruct("person", sv::Navigator(
        [](const void* p) -> const void* {
            const Event* s = static_cast<const Event*>(p);
            return static_cast<const void*>(s->person);
        }), "person");
    reg.registerStruct("rect", sv::Navigator(
        [](const void* p) -> const void* {
            const Event* s = static_cast<const Event*>(p);
            return static_cast<const void*>(&s->rect);
        }), "box");
    reg.registerProvider("feat_ids", sv::makeProvider(
        [](const void* p, const sv::DeviceCtx&) -> std::string {
            const Event* s = static_cast<const Event*>(p);
            static_assert(std::extent_v<decltype(s->feature_ids)> >= 8,
                          "struct_view: feature_ids length drift (schema count=8)");
            std::string out;
            char buf[256];
            for (std::size_t i = 0; i < 8; ++i) {
                if (i) out += "-";
                std::snprintf(buf, sizeof(buf), "%d", (int)s->feature_ids[i]);
                out += buf;
            }
            return out;
        }));
    reg.registerStructArray("boxes", sv::IndexedNavigator(
        [](const void* p, std::size_t i) -> const void* {
            const Event* s = static_cast<const Event*>(p);
            static_assert(std::extent_v<decltype(s->boxes)> >= 4,
                          "struct_view: boxes length drift (schema count=4)");
            return &s->boxes[i];
        }), "box", 4, "|");
    reg.registerProvider("name", sv::makeProvider(
        [](const void* p, const sv::DeviceCtx&) -> std::string {
            const PersonInfo* s = static_cast<const PersonInfo*>(p);
            char buf[256];
            std::snprintf(buf, sizeof(buf), "%s", (const char*)s->name);
            return std::string(buf);
        }));
    reg.registerProvider("age", sv::makeProvider(
        [](const void* p, const sv::DeviceCtx&) -> std::string {
            const PersonInfo* s = static_cast<const PersonInfo*>(p);
            char buf[256];
            std::snprintf(buf, sizeof(buf), "%d", (int)s->age);
            return std::string(buf);
        }));
    reg.registerProvider("x", sv::makeProvider(
        [](const void* p, const sv::DeviceCtx&) -> std::string {
            const Box* s = static_cast<const Box*>(p);
            char buf[256];
            std::snprintf(buf, sizeof(buf), "%d", (int)s->x);
            return std::string(buf);
        }));
    reg.registerProvider("y", sv::makeProvider(
        [](const void* p, const sv::DeviceCtx&) -> std::string {
            const Box* s = static_cast<const Box*>(p);
            char buf[256];
            std::snprintf(buf, sizeof(buf), "%d", (int)s->y);
            return std::string(buf);
        }));
    reg.registerProvider("w", sv::makeProvider(
        [](const void* p, const sv::DeviceCtx&) -> std::string {
            const Box* s = static_cast<const Box*>(p);
            char buf[256];
            std::snprintf(buf, sizeof(buf), "%d", (int)s->w);
            return std::string(buf);
        }));
    reg.registerProvider("h", sv::makeProvider(
        [](const void* p, const sv::DeviceCtx&) -> std::string {
            const Box* s = static_cast<const Box*>(p);
            char buf[256];
            std::snprintf(buf, sizeof(buf), "%d", (int)s->h);
            return std::string(buf);
        }));
    reg.registerProvider("tags", sv::makeProvider(
        [](const void* p, const sv::DeviceCtx&) -> std::string {
            const Box* s = static_cast<const Box*>(p);
            static_assert(std::extent_v<decltype(s->tags)> >= 2,
                          "struct_view: tags length drift (schema count=2)");
            std::string out;
            char buf[256];
            for (std::size_t i = 0; i < 2; ++i) {
                if (i) out += "-";
                std::snprintf(buf, sizeof(buf), "%d", (int)s->tags[i]);
                out += buf;
            }
            return out;
        }));
    reg.registerProvider("camera", sv::makeProvider(
        [](const void*, const sv::DeviceCtx& base) -> std::string {
            const MyDeviceCtx& ctx = static_cast<const MyDeviceCtx&>(base);
            return ctx.cameraId();
        }));
}
