#!/usr/bin/env python3
"""Generate registry_gen.cpp from a struct description (schema.json).

Usage: gen_registry.py schema.json output.cpp
Emits sv::NameRegistry registration calls referencing real struct members,
so layout drift fails the C++ build.
"""
import json, sys, pathlib

HEADER = """\
// AUTO-GENERATED by tools/gen_registry.py — DO NOT EDIT.
#include <struct_view/NameRegistry.hpp>
#include <struct_view/ValueProvider.hpp>
#include <struct_view/DeviceCtx.hpp>
#include <cstddef>
#include <cstdio>
#include <string>
#include <type_traits>

void registerStructViewNames(sv::NameRegistry& reg) {
"""

FOOTER = "}\n"

TYPE_CAST = {
    "uint64": "(unsigned long long)",
    "int":    "(int)",
    "float":  "(double)",
    "cstr":   "(const char*)",
}

def field_line(struct_name, member):
    field = member["field"]
    as_name = member.get("as", field)
    typ = member["type"]
    fmt = member["fmt"]
    cast = TYPE_CAST[typ]
    # cstr: char arrays decay; cast to const char* is safe for char[N] and char*
    return f'''    reg.registerProvider("{as_name}", sv::makeProvider(
        [](const void* p, const sv::DeviceCtx&) -> std::string {{
            const {struct_name}* s = static_cast<const {struct_name}*>(p);
            char buf[256];
            std::snprintf(buf, sizeof(buf), "{fmt}", {cast}s->{field});
            return std::string(buf);
        }}));\n'''

def block_line(struct_name, member):
    block = member["block"]
    sub = member["subRecipe"]
    ptr = member.get("ptr", False)
    deref = f"static_cast<const void*>(s->{block})" if ptr else f"static_cast<const void*>(&s->{block})"
    return f'''    reg.registerStruct("{block}", sv::Navigator(
        [](const void* p) -> const void* {{
            const {struct_name}* s = static_cast<const {struct_name}*>(p);
            return {deref};
        }}), "{sub}");\n'''

def field_array_line(struct_name, member):
    field = member["field"]
    as_name = member.get("as", field)
    typ = member["type"]
    fmt = member["fmt"]
    arr = member["array"]
    count = arr["count"]
    sep = arr["sep"]
    cast = TYPE_CAST[typ]
    sep_lit = sep.replace('\\', '\\\\').replace('"', '\\"')
    return f'''    reg.registerProvider("{as_name}", sv::makeProvider(
        [](const void* p, const sv::DeviceCtx&) -> std::string {{
            const {struct_name}* s = static_cast<const {struct_name}*>(p);
            static_assert(std::extent_v<decltype(s->{field})> >= {count},
                          "struct_view: {field} length drift (schema count={count})");
            std::string out;
            char buf[256];
            for (std::size_t i = 0; i < {count}; ++i) {{
                if (i) out += "{sep_lit}";
                std::snprintf(buf, sizeof(buf), "{fmt}", {cast}s->{field}[i]);
                out += buf;
            }}
            return out;
        }}));\n'''

def block_array_line(struct_name, member):
    block = member["block"]
    arr = member["array"]
    sub = arr["subRecipe"]
    count = arr["count"]
    sep = arr["sep"]
    sep_lit = sep.replace('\\', '\\\\').replace('"', '\\"')
    return f'''    reg.registerStructArray("{block}", sv::IndexedNavigator(
        [](const void* p, std::size_t i) -> const void* {{
            const {struct_name}* s = static_cast<const {struct_name}*>(p);
            static_assert(std::extent_v<decltype(s->{block})> >= {count},
                          "struct_view: {block} length drift (schema count={count})");
            return &s->{block}[i];
        }}), "{sub}", {count}, "{sep_lit}");\n'''

def device_line(device_ctx_type, dev):
    getter = dev["getter"]
    as_name = dev.get("as", getter)
    return f'''    reg.registerProvider("{as_name}", sv::makeProvider(
        [](const void*, const sv::DeviceCtx& base) -> std::string {{
            const {device_ctx_type}& ctx = static_cast<const {device_ctx_type}&>(base);
            return ctx.{getter}();
        }}));\n'''

def validate_member(struct_name, m):
    """Validate a single member's shape; raise ValueError with a clear message
    if malformed (so schema typos fail the build loudly, not silently)."""
    has_field, has_block, has_array = "field" in m, "block" in m, "array" in m
    # 1. Must have exactly one of field/block (the C member to read). 'array' alone
    #    (no field/block) is a typo like {"bloc": ..., "array": ...} — would be
    #    silently skipped without this check.
    if not has_field and not has_block:
        raise ValueError(
            f"struct_view schema: struct '{struct_name}' has a member with neither "
            f"'field' nor 'block' (got keys: {sorted(m.keys())}); cannot determine "
            f"which C member to read. Did you typo 'field'/'block'?")
    if has_field and has_block:
        raise ValueError(
            f"struct_view schema: struct '{struct_name}' member has both 'field' and "
            f"'block' — a member is either a scalar field or a struct block, not both.")
    # 2. Array members need a well-formed 'array' object.
    if has_array:
        arr = m["array"]
        if not isinstance(arr, dict):
            raise ValueError(
                f"struct_view schema: struct '{struct_name}' member '{m.get('field') or m.get('block')}' "
                f"has 'array' that is not an object (got {type(arr).__name__}).")
        if "count" not in arr:
            raise ValueError(
                f"struct_view schema: struct '{struct_name}' member '{m.get('field') or m.get('block')}' "
                f"is an array but 'array' is missing required key 'count'.")
        if "sep" not in arr:
            raise ValueError(
                f"struct_view schema: struct '{struct_name}' member '{m.get('field') or m.get('block')}' "
                f"is an array but 'array' is missing required key 'sep'.")
        if has_block and "subRecipe" not in arr:
            raise ValueError(
                f"struct_view schema: struct '{struct_name}' struct-array '{m['block']}' "
                f"is missing 'array.subRecipe' (which sub-recipe each element runs).")
        if has_field and ("type" not in m or "fmt" not in m):
            missing = "type" if "type" not in m else "fmt"
            raise ValueError(
                f"struct_view schema: struct '{struct_name}' scalar-array '{m['field']}' "
                f"is missing required key '{missing}' (element type/format).")

def gen(schema):
    device_ctx_type = schema.get("deviceCtxType", "sv::DeviceCtx")
    out = HEADER
    for st in schema.get("structs", []):
        sn = st["name"]
        for m in st.get("members", []):
            validate_member(sn, m)   # fail loud on malformed members (M-5)
            if "array" in m:
                if "field" in m:
                    out += field_array_line(sn, m)
                elif "block" in m:
                    out += block_array_line(sn, m)
            elif "field" in m:
                out += field_line(sn, m)
            elif "block" in m:
                out += block_line(sn, m)
    for d in schema.get("device", []):
        out += device_line(device_ctx_type, d)
    out += FOOTER
    return out

def main():
    if len(sys.argv) != 3:
        print("usage: gen_registry.py schema.json output.cpp", file=sys.stderr)
        sys.exit(2)
    try:
        schema = json.loads(pathlib.Path(sys.argv[1]).read_text())
    except json.JSONDecodeError as ex:
        print(f"gen_registry.py: schema.json is not valid JSON: {ex}", file=sys.stderr)
        sys.exit(1)
    try:
        out = gen(schema)
    except ValueError as ex:
        print(f"gen_registry.py: {ex}", file=sys.stderr)
        sys.exit(1)
    pathlib.Path(sys.argv[2]).write_text(out)

if __name__ == "__main__":
    main()
